let name="Kishan Singh";
let school="PSIT";
let grade="B";
let section="ME-A";
let rollno=436;
let mathematics=83;
let physics=91;
let english=79;
console.log("name -", name);
console.log("school -",school);
console.log("grade -",grade);
console.log("section -",section);
console.log("rollno =",rollno);
console.log("mathematics =",mathematics);
console.log("physics =",physics);
console.log("english =",english);
